### PR TITLE
List structure

### PR DESCRIPTION
**Pull request by BenMukebo**
> ## These are what was done to build a simple HTML list of To Do tasks:
> 
> - [ ] Set up a new project with webpack,
> - [ ] Create an index.html file and write the HTML markup,
> - [ ] Create an index.js and data.js file and set an array of objects, Each task object contains three keys:
> * description [string].
> * completed [bool].
> * index: [number].
> - [ ] Write a function to iterate over the tasks array and populate an HTML list item element for each task,
> - [ ] Create a style.css and set rules for the To Do List,
> - [ ]  Fix all linter errors,
> - [ ]  Create a descriptive README file.

### CODE REVIEW

**Review by Dipeshtwis — COMMENTED** [review]
# Status: Invalid ❌

## Hi @BenMukebo,
Please fix the issue mentioned below and then request for code review

## Reason

- [ ] I think you have submitted the wrong project. From your PR it looks like you are about to request for "To-Do List: list structure" instead of "interactive list".

### Please make sure to submit code review when you are done with the changes that was requested

**Don't worry you still have same number of requests left as previous.**


Cheers and Happy Coding :clap: :clap: :clap: 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

**_Dipesh Kumar_**

**Review by barackm — APPROVED** [review]
Hi @BenMukebo, 👋 

# STATUS: Approved  🎉 
Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by BenMukebo** [comment]
import './style.css';
import sortItems from './utils.js';
import tasks from './data.js';
import completedTask from './controllers.js';
import storage from './storage.js';

const taskList = document.querySelector('.task-list');
const getTask = (tasks) => {
  taskList.innerHTM = '';
  console.log(tasks);

// Give books to the ul and display it from UI
  tasks.map((task) => {
    const li = document.createElement('li');
    li.classList.add('book', 'd-flex', 'flex-center');
    li.innerHTML = ` <span class="left">
      <input class="checkbox" id=${task.index} type="checkbox" />
      <label class="title" for=${task.index}>${task.description}</label>
    </span>
    <span class="right">
      <i class="fas fa-ellipsis-v"></i>
    </span>`;
    return taskList.appendChild(li);
  });

  const books = document.querySelectorAll('.book');
  // console.log(books);

  books.forEach((box) => {
    const checkBox = box.querySelector('.checkbox');
    const label = box.querySelector('.title');
    const icon = box.querySelector('.right i');

    let state = false;
    checkBox.addEventListener('click', () => {
      if (!state) {
        label.classList.add('compeleted');
        state = true;
      } else {
        label.classList.remove('compeleted');
        state = false;
      }
      const taskId = checkBox.id;
      completedTask(taskId);
    });

    let change = false;
    icon.addEventListener('click', () => {
      const indexBox = checkBox.id;
      console.log('book Index:', indexBox);
      if (!change) {
        box.classList.add('active');
        icon.classList.remove('fas', 'fa-ellipsis-v');
        icon.classList.add('far', 'fa-trash-alt');
        change = true;
      } else {
// Function for adding a new task
        const getTasks = storage.getItem();
        const sortedTasks = sortItems(getTasks);
        const filterTasks = sortedTasks.filter((book) =>
book.index.toString() !== indexBox);
        storage.setItem(filterTasks);
        taskList.innerHTML = '';
        getTask(filterTasks);
      }
    });
  });
};

let getTasks;

(function setTaks() {
  if (!storage.getItem()) {
    storage.setItem(tasks);
    getTasks = storage.getItem();
  } else {
    getTasks = storage.getItem();
  }
}());

window.onload = () => {
  const sortedTasks = sortItems(getTasks);
  getTask(sortedTasks);
};

class Task {
  constructor(description, index) {
    this.description = description;
    this.completed = false;
    this.index = index;
  }
}

// Function for adding a new task

const form = document.querySelector('#form');

form.addEventListener('submit', (e) => {
  e.preventDefault();
  const enterTask = document.querySelector('#task-input').value;
  if (enterTask === '') return;

  const getTasks = storage.getItem() || [];
  const sortedTasks = sortItems(getTasks);
  let index = sortedTasks.length;
  index += 1;
  const newTask = new Task(enterTask, index);
  // console.log(newTask);

  sortedTasks.push({
    completed: newTask.completed,
    index: newTask.index,
    description: newTask.description,
  });
  storage.setItem(sortedTasks);
  taskList.innerHTM = '';
  getTask(sortedTasks);
  // console.log(sortedTasks);
  // enterTask.value = '';
});

**Comment by BenMukebo** [comment]
import './style.css';
import sortItems from './utils.js';
// import tasks from './data.js';
import completedTask from './controllers.js';
import storage from './storage.js';

const tasks = storage.getItem();
console.log(tasks);
const taskList = document.querySelector('.task-list');
const getTask = (task) => {
taskList.innerHTML += `<li class="book d-flex flex-center">
<span class="left">
<input class="checkbox" id=${task.index} type="checkbox" />
<input class="editInput" type="text" value="${task.description}" />
<label class="title" for=${task.index}.>${task.description}</label>
</span>
<span class="right">
<i class="fas fa-ellipsis-v"></i>
</span>
</li>`;

const books = document.querySelectorAll('.book');
// console.log(books)

books.forEach((box, index) => {
const checkBox = box.querySelector('.checkbox');
const label = box.querySelector('.title');
const icon = box.querySelector('.right i');
const edit = box.querySelector('.editInput');

let state = false;
checkBox.addEventListener('click', () => {
if (!state) {
label.classList.add('compeleted');
state = true;
} else {
label.classList.remove('compeleted');
state = false;
}
const taskId = checkBox.id;
completedTask(taskId);
});

let change = false;
icon.addEventListener('click', () => {
const indexBox = checkBox.id;
if (!change) {
box.classList.add('active');
icon.classList.remove('fas', 'fa-ellipsis-v');
icon.classList.add('far', 'fa-trash-alt');

edit.style.display = 'flex';
label.style.display = 'none';
change = true;
} else {
// Function for deleting a new task
const getTasks = storage.getItem();
const sortedTasks = sortItems(getTasks);
const filterTasks = sortedTasks.filter((book) => book.index.toString() !==
indexBox);
// console.log(taskList.innerHTM);
storage.setItem(filterTasks);
taskList.innerHTML = '';
filterTasks.forEach((task) => {
getTask(task);
});
}
});
edit.addEventListener('keydown', (e) => {
if (e.key === 'Enter') {
const { value } = edit;
console.log(value);
tasks.forEach((task, ind) => {
if (index === ind) {
task.description = value;
tasks.splice(ind, 1, task);
storage.setItem(tasks);
box.classList.remove('active');
icon.classList.remove('far', 'fa-trash-alt');
icon.classList.add('fas', 'fa-ellipsis-v');

edit.style.display = 'none';
label.style.display = 'flex';
window.location.reload();
}
return false;
});
}
});
});
};

let getTasks;

(function setTaks() {
if (!storage.getItem()) {
storage.setItem(tasks);
getTasks = storage.getItem();
} else {
getTasks = storage.getItem();
}
}());

window.onload = () => {
const sortedTasks = sortItems(getTasks);
sortedTasks.forEach((task) => {
getTask(task);
});
};

class Task {
constructor(description, index) {
this.description = description;
this.completed = false;
this.index = index;
}
}

// Function for adding a new task

const form = document.querySelector('#form');

form.addEventListener('submit', (e) => {
e.preventDefault();
const enterTask = document.querySelector('#task-input');
if (enterTask === '') return;

const getTasks = storage.getItem() || [];
const sortedTasks = sortItems(getTasks);
let index = sortedTasks.length;
index += 1;
const newTask = new Task(enterTask.value, index);
// console.log(newTask);

sortedTasks.push(newTask);
storage.setItem(sortedTasks);

getTask(newTask);
enterTask.value = '';
});

// Function for Clear all completed a new task

**Comment by BenMukebo** [comment]
import sortItems from './utils.js';
import storage from './storage.js';

const completedTask = (id) => {
const getTasks = storage.getItem();
const sortedTasks = sortItems(getTasks);
sortedTasks.forEach((task) => {
if (task.index.toString() === id) {
task.completed = !task.completed;
}
});
storage.setItem(sortedTasks);
};

const removeCompletedTask = (tasks) => {
let compeletedTasks = tasks.filter((task) => task.completed === false);
compeletedTasks = compeletedTasks.map((item, index) => {
item.index = index + 1;
return item;
});
return compeletedTasks;
};

export { removeCompletedTask, completedTask };

**Comment by BenMukebo** [comment]
import './style.css';
import sortItems from './utils.js';
// import tasks from './data.js';
import { completedTask, removeCompletedTask } from './controllers.js';
import storage from './storage.js';

const tasks = storage.getItem();
// console.log(tasks);
const taskList = document.querySelector('.task-list');
// const filters;

const getTask = (task) => {
taskList.innerHTML += `<li class="book d-flex flex-center">
<span class="left d-flex flex-center">
<input class="checkbox" ${task.completed ? 'checked' : ''} id=${task.index}
type="checkbox" />
<input class="editInput" type="text" value="${task.description}" />
<label class="${task.completed ? 'title compeleted' : 'title'}" for=${task.
index}.>${task.description}</label>
</span>
<span class="right">
<i class="fas fa-ellipsis-v"></i>
</span>
</li>`;

const books = document.querySelectorAll('.book');
// console.log(books)

books.forEach((box, index) => {
const checkBox = box.querySelector('.checkbox');
const inputEdit = box.querySelector('.editInput');
const label = box.querySelector('.title');
const icon = box.querySelector('.right i');
let change = false;

// Check box action

checkBox.addEventListener('click', () => {
const taskId = checkBox.id;
completedTask(taskId);
const tasks = storage.getItem();
taskList.innerHTML = '';
tasks.forEach((task) => {
getTask(task);
});
});

// Icons action

icon.addEventListener('click', () => {
const indexBox = checkBox.id;
if (!change) {
box.classList.add('active');
icon.classList.remove('fas', 'fa-ellipsis-v');
icon.classList.add('far', 'fa-trash-alt');

inputEdit.style.display = 'flex';
label.style.display = 'none';
change = true;
} else {
// Function for deleting a new task

const getTasks = storage.getItem();
const sortedTasks = sortItems(getTasks);
let filterTasks = sortedTasks.filter((book) => book.index.toString() !==
indexBox);
// console.log(taskList.innerHTM);
filterTasks = filterTasks.map((item, index) => {
item.index = index + 1;
return item;
});
storage.setItem(filterTasks);
taskList.innerHTML = '';
filterTasks.forEach((task) => {
getTask(task);
});
}
});

// Function for editing task descriptions.

inputEdit.addEventListener('keydown', (e) => {
if (e.key === 'Enter') {
const { value } = inputEdit;
console.log(value);
tasks.forEach((task, ind) => {
if (index === ind) { /// ////
task.description = value;
tasks.splice(ind, 1, task);
storage.setItem(tasks);
box.classList.remove('active');
icon.classList.remove('far', 'fa-trash-alt');
icon.classList.add('fas', 'fa-ellipsis-v');

inputEdit.style.display = 'none';
label.style.display = 'flex';
window.location.reload();
}
return false;
});
}
});
});
};

let getTasks;
console.log('heiaaoiuhewiuhgoiugfhesgoahgewiuoh');
(function setTaks() {
if (!storage.getItem()) {
storage.setItem(tasks);
getTasks = storage.getItem();
} else {
getTasks = storage.getItem();
}
}());

window.onload = () => {
const sortedTasks = sortItems(getTasks);
sortedTasks.forEach((task) => {
getTask(task);
});
};

class Task {
constructor(description, index) {
this.description = description;
this.completed = false;
this.index = index;
}
}

// Function for adding a new task

const form = document.querySelector('#form');

form.addEventListener('submit', (e) => {
e.preventDefault();
const enterTask = document.querySelector('#task-input');
if (enterTask === '') return;

const getTasks = storage.getItem() || [];
const sortedTasks = sortItems(getTasks);
const index = sortedTasks.length + 1;
const newTask = new Task(enterTask.value, index);
// console.log(newTask);

sortedTasks.push(newTask);
storage.setItem(sortedTasks);

getTask(newTask);
enterTask.value = '';
});

// Function for Clear all completed a new task

const clearBtn = document.querySelector('#clear');

clearBtn.addEventListener('click', () => {
const tasks = storage.getItem();
const completedTasks = removeCompletedTask(tasks);
console.log(completedTasks);
storage.setItem(completedTasks);
taskList.innerHTML = '';
const newTasks = storage.getItem();
newTasks.forEach((task) => {
getTask(task);
});
});

**Pull request merged**
